/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CelebrationOverlay: typeof import('./src/components/CelebrationOverlay.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    ControlPanel: typeof import('./src/components/ControlPanel.vue')['default']
    DartKeypad: typeof import('./src/components/DartKeypad.vue')['default']
    LeaderboardTable: typeof import('./src/components/LeaderboardTable.vue')['default']
    OperatorPanel: typeof import('./src/components/OperatorPanel.vue')['default']
    PlayerSearch: typeof import('./src/components/PlayerSearch.vue')['default']
    PlayerSelect: typeof import('./src/components/PlayerSelect.vue')['default']
    PlayersPanel: typeof import('./src/components/PlayersPanel.vue')['default']
    RoundEditor: typeof import('./src/components/RoundEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
